services:
  db:
    image: postgres:16-alpine
    container_name: opticplace_db
    environment:
      POSTGRES_DB: opticplace
      POSTGRES_USER: opticplace
      POSTGRES_PASSWORD: opticplace
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: